//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeamDBEntities : DbContext
    {
        public TeamDBEntities()
            : base("name=TeamDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T001_Teams> T001_Teams { get; set; }
        public virtual DbSet<T002_Player> T002_Player { get; set; }
        public virtual DbSet<T003_Event> T003_Event { get; set; }
    }
}
