//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class T002_Player
    {
        public int Id { get; set; }
        public string Prename { get; set; }
        public string Surname { get; set; }
        public int Number { get; set; }
        public int TeamId { get; set; }
    }
}
